### ISSUE TITLE
Internet Explorer : Object doesn't support property or method 'contains'

### ISSUE THREAD

**Issue by pkurimella** [google/google-visualization-issues#2039] opened 2015-08-25 19:22 UTC
Getting this error in Internet Explorer only. This started happening after the new version was released.
![image](https://cloud.githubusercontent.com/assets/8547172/9476884/1f7a969c-4b3d-11e5-91f1-80c7c83c01de.png)

**Comment by grabks** [comment] 2015-08-25 19:27
Hi, it looks like you might be using a Material Chart or perhaps Gantt? Can you please link to a jsfiddle reproducing this issue?

**Comment by pkurimella** [comment] 2015-08-26 14:06
I'm unable to reproduce this issue in jsfiddle. The condition this happens is I have 3 tabs and i'm loading the graphs on tab select. The first graph is the one with the tab selected by default and renders fine. When I switch to other two tabs and try to load the graph I get the above error.

Another question I have is do I have to load visualization package for each graph independently?

**Comment by grabks** [comment] 2015-08-26 14:24
You still haven't mentioned which chart you're using.

If this is the issue that I'm thinking of, it would occur on subsequent redraws, so you should be able to work around the issue either by a) drawing all the charts and then setting display: none on the relevant ones, or b) by reinstantiating the charts instead of just redrawing them.

You should only have one google.load('visualization', ...) call on your page. Multiple calls might cause undefined behavior or unforeseen issues.

**Comment by pkurimella** [comment] 2015-08-26 16:22
Please run the below in Internet Explorer. I could reproduce the issue in IE
https://jsfiddle.net/fjd76a49/3/

**Comment by pkurimella** [comment] 2015-08-26 16:34
I tried loading multiple graphs at once and looks like the second graph load always errors out in Internet Explorer. Ref https://jsfiddle.net/fjd76a49/4/

**Comment by grabks** [comment] 2015-08-26 17:17
Ah, so this is the issue that I was thinking of. Unfortunately, this is a known bug in v42. It will be fixed when we release v43 (which should be in a week or so). In the meanwhile, you can switch your implementation to use the frozen version v41. Here is an example of doing that: https://jsfiddle.net/fjd76a49/6/

**Comment by pkurimella** [comment] 2015-08-26 20:29
Thanks it worked. I'm assuming this (frozen v41) would future proof us from any bugs in the newer releases?

**Closed as completed** 2015-08-26 20:29 UTC

**Comment by dlaliberte** [comment] 2015-08-26 20:33
We won't be changing the frozen v41, so it should stay the same.  However, we are changing the loader, so this _could_ affect previous versions (negatively), though we will certainly try hard to avoid that.

**Comment by rjbathgate** [comment] 2015-09-30 10:00
Hi

I am experiencing exactly the same issue here, when showing two graphs.

Using: google.load("visualization", "1.1", {packages:["bar"]});) 

in IE11 - the second graph doesn't load and returns:

Object doesn't support property or method 'contains'.

I swapped out the second graph to use https://www.gstatic.com/charts/loader.js and google.charts.load('41', {packages: ['corechart', 'bar']}); however that caused a few other bugs (on hover of columns etc).

Should this be "fixed" by now (i.e. is v43 out yet?) or is something else going on for me?

Thanks
