### ISSUE TITLE
Bug: Impossible to hide tooltips in material bar/column charts

### ISSUE THREAD

**Issue by orwant** [google/google-visualization-issues#1919] opened 2015-05-09 17:48 UTC
```
What steps will reproduce the problem? Please provide a link to a
demonstration page if at all possible, or attach code.
1. Try to use properties such as enableInteractivity: false, within the options object
but the chart omits them and therefore, the tooltips are always displayed when the
mouse is over the chart.
2. Try to use properties such as tooltip: {trigger: 'none' } within the options object
but the chart omits them and and therefore, the tooltips are always displayed when
the mouse is over the chart.

3. The same worked perfectly in previous versions of the bar chart.

What component is this issue related to (PieChart, LineChart, DataTable,
Query, etc)? Column chart and Bar chart as far as I know

Are you using the test environment (version 1.1)? Yes
(If you are not sure, answer NO)


What operating system and browser are you using? Linux (Debian) + Chrome



*********************************************************
For developers viewing this issue: please click the 'star' icon to be
notified of future changes, and to let us know how many of you are
interested in seeing it resolved.
*********************************************************

```

Original issue reported on code.google.com by `diego.casadomansilla` on 2015-03-12 12:18:10

**Comment by orwant** [comment] 2015-05-09 17:48
```
(No text was entered with this change)
```

Original issue reported on code.google.com by `grabks@google.com` on 2015-03-12 13:36:47
- **Labels added**: Type-Enhancement
- **Labels removed**: Type-Defect

**Comment by orwant** [comment] 2015-05-09 17:48
```
(No text was entered with this change)
```

Original issue reported on code.google.com by `grabks@google.com` on 2015-03-12 13:36:57

**Comment by grabks** [comment] 2016-01-13 15:55
Closing as a duplicate of https://github.com/google/google-visualization-issues/issues/2143

**Closed as completed by grabks** 2016-01-13 15:55 UTC
Labels: Priority-Medium, Type-Enhancement
