### ISSUE TITLE
Material + bar chart + tooltip.isHtml does not seem to work

### ISSUE THREAD

**Issue by cjblomqvist** [google/google-visualization-issues#2016] opened 2015-08-04 21:55 UTC
See https://jsfiddle.net/cjblomqvist/uuLnp834/1/ for an example. I need isHtml in order to use ignoreBounds, and apparently it is not working (I've also checked the DOM - it renders SVG and no regular HTML).

Or am I missing something?

**Comment by trevordowdle** [comment] 2016-01-13 04:13
Running into same problem

**Comment by nbering** [comment] 2016-01-13 14:47
Possibly related to #1946 and #1953? Smells like unimplemented features in the new charts.

**Comment by grabks** [comment] 2016-01-13 15:15
Good instincts, @nbering, this is exactly the case.

HTML tooltips are not yet supported in Material charts.

**Comment by grabks** [comment] 2016-01-13 15:52
Closing as a duplicate of https://github.com/google/google-visualization-issues/issues/2143

**Closed as completed by grabks** 2016-01-13 15:52 UTC
Labels: enhancement
