### ISSUE TITLE
Bug: Uncaught ReferenceError: Hh is not defined

### ISSUE THREAD

**Issue by sdrenth** [google/google-visualization-issues#2178] opened 2016-02-25 09:53 UTC
The Pie Chart stopped working on my website, but on the detailpages of Google Visualization I get the same error. The charts on the gallery page are working.

Charts overview:
https://google-developers.appspot.com/chart/interactive/docs/gallery

Charts detail:
https://google-developers.appspot.com/chart/interactive/docs/gallery/piechart

It appears that the error occurs when using loader.js:
https://www.gstatic.com/charts/loader.js

**Comment by pbaan93** [comment] 2016-02-25 10:09
Same here.

Can't see google charts.

Error is on all charts, for example here:  https://developers.google.com/chart/interactive/docs/gallery/gauge
Console: "Uncaught ReferenceError: Hh is not defined"

I'm using windows 10, problem in all browsers

**Comment by sdrenth** [comment] 2016-02-25 10:16
I've managed to get it to work by using the loader below instead of loader.js:
https://www.google.com/jsapi?autoload={%22modules%22%3A%5B{%22name%22%3A%22visualization%22%2C%22version%22%3A%221%22%2C%22packages%22%3A%5B%22corechart%22,%20%22treemap%22,%20%22geomap%22,%20%22gauge%22,%20%22table%22,%20%22timeline%22,%20%22orgchart%22%5D}%5D}

For rendering the charts I used this script as a guideline:
https://google-developers.appspot.com/chart/interactive/js/gallery.js

**Comment by dlaliberte** [comment] 2016-02-25 14:27
I just announced release of v44, and it appears that when we push out a new version, there are some hiccups in the system until the changes fully propagate.  If you get these kinds of errors, I suggest you refresh the page, flushing your cache if necessary.  If a problem persists, please give us enough details, such as a working example, so that we can determine the cause of the problem.  Thanks.

**Comment by jackozi** [comment] 2016-02-25 16:27
Since last night I am getting this error as well. Just loading the API  ([JSFiddle](https://jsfiddle.net/qdp8n1qn/)) is enough to invoke it. Tried on different machines and in different browsers. 

```
ReferenceError: Hh is not defined
 loader.js line 133 > eval:303:445
```

**Comment by jackozi** [comment] 2016-02-25 16:37
Just after I posted that the error stopped appearing. Thank you

**Comment by dlaliberte** [comment] 2016-02-25 16:37
I just announced release of v44, and it appears that when we push out a new
version, there are some hiccups in the system until the changes fully
propagate.  We will be working to fix this in the future, but for now, if
you get these kinds of errors, I suggest you refresh the page, flushing
your cache if necessary.  If a problem persists, please give us enough
details, such as a "working" example, so that we can determine the cause of
the problem.  Thanks.

@Jackozi, we are not seeing a problem with your jsfiddle.  Thanks for
posting it though.

On Thu, Feb 25, 2016 at 11:27 AM, jackozi notifications@github.com wrote:

> Since last night I am getting this error as well. Just loading the API (
> JSFiddle https://jsfiddle.net/qdp8n1qn/) is enough to invoke it. Tried
> on different machines and in different browsers.
> 
> ReferenceError: Hh is not defined
>  loader.js line 133 > eval:303:445
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/google/google-visualization-issues/issues/2178#issuecomment-188863099
> .

## 

Daniel LaLiberte https://plus.google.com/100631381223468223275?prsrc=2
dlaliberte@Google.com dlaliberte@google.com   5CC, Cambridge MA

**Comment by Vasilisck** [comment] 2016-02-25 16:39
same here:

Uncaught ReferenceError: Hh is not defined(anonymous function) @ VM11617:303e @ loader.js:133google.a.c.Xc @ loader.js:134google.a.c.Oa @ loader.js:144google.a.Oa @ loader.js:144(anonymous function) @ jsapi_compiled_corechart_module.js:1

 type="text/javascript" src="https://www.gstatic.com/charts/loader.js"

edit: same device, different browsers, cache clear

**Comment by Gibelli** [comment] 2016-02-25 20:49
I am having a similar trouble: 
Uncaught TypeError: google.visualization.PieChart is not a function. It returns the same error with LineChart and ColumnChart

Yesterday my charts were rendering properly, but today they suddenly stopped.

I tried to render the code contained in the quick start page [https://developers.google.com/chart/interactive/docs/quick_start], but it gives the same error

**Comment by dlaliberte** [comment] 2016-02-25 20:52
If you just want to get your charts working again, you could change the
version you load from 'current' to '43'.

On Thu, Feb 25, 2016 at 3:49 PM, Gibelli notifications@github.com wrote:

> I am having a similar trouble:
> Uncaught TypeError: google.visualization.PieChart is not a function
> 
> Yesterday my charts were rendering properly, but today they suddenly
> stopped.
> 
> I tried to render the code contained in the quick start page [
> https://developers.google.com/chart/interactive/docs/quick_start], but it
> gives the same error
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/google/google-visualization-issues/issues/2178#issuecomment-188978945
> .

## 

Daniel LaLiberte https://plus.google.com/100631381223468223275?prsrc=2
dlaliberte@Google.com dlaliberte@google.com   5CC, Cambridge MA

**Comment by Gibelli** [comment] 2016-02-25 21:28
It`s working again. Thanks a lot!

Question: did you guys deprecate this function or is it just a consequence of the system instability?

**Comment by dlaliberte** [comment] 2016-02-25 22:09
We did nothing here.  The charts will start working correctly again once
the server and your browsers sync up with the current release.   We will
find a better way to do this in the near future.

On Thu, Feb 25, 2016 at 4:28 PM, Gibelli notifications@github.com wrote:

> It`s working again. Thanks a lot!
> 
> Question: did you guys deprecate this function or is it just a consequence
> of the system instability?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/google/google-visualization-issues/issues/2178#issuecomment-188995875
> .

## 

Daniel LaLiberte https://plus.google.com/100631381223468223275?prsrc=2
dlaliberte@Google.com dlaliberte@google.com   5CC, Cambridge MA

**Comment by viveksg** [comment] 2016-03-02 13:40
I faced this issue today.
But my charts were working fine once i switched to old code.
------OLD CODE-----
`<script type="text/javascript" src="https://www.google.com/jsapi"></script>`
`google.load('visualization', '1.0', {'packages':['corechart']});`

And whenever I was switching to new code I was having this issue
-----NEW CODE-------
`<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>`
`google.charts.load('current', {'packages':['corechart','controls','annotatedtimeline','gauge','table']});`

I changed 'current' to '43' ,in "google.charts.load...." and things were working fine.
Then I cleared browser data (everything) and changed 'current' to 44
and code was working fine.
I cleared browser data again and changed '44' to current and this bug appeared again.

question: How 'current' is mapped to current version?

**Comment by grabks** [comment] 2016-03-02 15:59
@viveksg It sounds like you are experiencing the issues caused by caching and
propagation delays of our latest release. These issues should fix
themselves eventually (probably in a few days). In the meantime, you can
workaround it by explicitly specifying a version, such as `'43'` or `'44'` instead
of `'current'` or `'upcoming'` as you currently do.

To answer your question more directly, 'current' is mapped to the current
version via a redirect for each package. This is why the errors are
occurring: some packages are served from 43, and some are served from 44. I
certainly can't understand why the issue would occur after you clear the
cache.

**Comment by rusterholz** [comment] 2016-03-02 18:36
This issue just started occurring for me. I'll try changing 'current' to different values and see if I can fix it.

Of all the companies to have an issue keeping servers in sync when a new version of code is deployed, I would not expect it to be Google... ;-)

**Comment by grabks** [comment] 2016-03-02 18:38
@rusterholz We were also very surprised to discover these issues.

Closing this bug as a duplicate of #2185.

**Closed as completed by grabks** 2016-03-02 18:38 UTC
