### ISSUE TITLE
google.visualizations.Bar Animation

### ISSUE THREAD

**Issue by jaredrakoff** [google/google-visualization-issues#2009] opened 2015-07-16 18:42 UTC
Animations not working for Material Charts

**Comment by retox001** [comment] 2015-07-22 13:05
Is anyone looking into this? provide an update? or could anyone provide information as to why animation are not supported currently with the material charts? i am aware that it is still in beta but currently i am unable to get any material charts to animate.

If anyone has got any of the material charts to animate please let me know and provide a demo link :-)

**Comment by grabks** [comment] 2015-07-22 13:46
Material Charts were rebuilt from scratch, and so do not support many features that you might be used to, including animation. This is also the primary reason why the charts are in "beta". We are currently prioritizing other, less user-visible work, so it might take a while until we get around to implementing this feature.

**Comment by retox001** [comment] 2015-07-22 14:10
Ok no problem, thanks for the quick response to my query :-)
I would suggest updating the guides to state that the animations are not currently supported with the material charts.

**Comment by larshp** [comment] 2015-10-18 15:04
+1

**Comment by grabks** [comment] 2016-01-13 15:53
Closing as a duplicate of https://github.com/google/google-visualization-issues/issues/2143

**Closed as completed by grabks** 2016-01-13 15:53 UTC
Labels: enhancement
