### ISSUE TITLE
Bug: interpolateNulls does not work on material linechart

### ISSUE THREAD

**Issue by orwant** [google/google-visualization-issues#1962] opened 2015-05-09 17:49 UTC
```
(No text was entered with this change)
```

Original issue reported on code.google.com by `None` on 1970-01-01T00:00:00.00Z

**Comment by grabks** [comment] 2016-01-13 15:53
Closing as a duplicate of https://github.com/google/google-visualization-issues/issues/2143

**Closed as completed by grabks** 2016-01-13 15:53 UTC
Labels: Type-Defect, Priority-Medium
