### ISSUE TITLE
Google map visualisation not working for named locations

### ISSUE THREAD

**Issue by jeffdbelcher** [google/google-visualization-issues#2698] opened 2018-12-07 19:33 UTC
This issue can be seen on Google's own gallery:

https://developers.google.com/chart/interactive/docs/gallery/map

"No data points to show on map" is being displayed for map visualisations using named locations rather than lat/long.

**Comment by nbering** [comment] 2018-12-08 04:28
Console errors on the docs page indicate that it's an API key issue for the geocoding service.

**Comment by dlaliberte** [comment] 2018-12-11 20:53
Duplicate of #2699

**Closed as completed by dlaliberte** 2018-12-11 20:53 UTC
Labels: duplicate
