### ISSUE TITLE
jsfiddle example not working

### ISSUE THREAD

**Issue by gmorphis** [google/google-visualization-issues#2198] opened 2016-03-02 19:32 UTC
Tried in both Chrome 48.0.2564.116 m and Firefox 41.0.1
I click run and nothing happens. I copied the code locally and I get a:
Uncaught TypeError: Cannot read property 'left' of undefined
VM205:98

**Comment by grabks** [comment] 2016-03-02 19:36
@gmorphis What jsfiddle example are you referring to?

**Comment by gmorphis** [comment] 2016-03-02 19:40
My apologies, I'm new here.
https://developers.google.com/chart/interactive/docs/gallery/orgchart?csw=1
I clicked on the Issues and Requests at the bottom of the page and was
taken to the forum. I assumed it was related but you know what they say
about assumptions.

Thanks!

**Comment by grabks** [comment] 2016-03-02 19:43
So to verify, [this](https://jsfiddle.net/rtgb01rc/) is the jsfiddle that doesn't work for you?

How about [this one](https://jsfiddle.net/2Loccfpx/) or [this one](https://jsfiddle.net/qb1u24b7/)?

**Comment by gmorphis** [comment] 2016-03-02 19:47
Yes! That one. The 2 additional ones you have do work. I'll go off that
sample code. Thanks!

**Comment by grabks** [comment] 2016-03-02 19:51
Thanks for your quick responses!

It sounds like you're experiencing the issues caused by caching and propagation delays of our latest release. These issues should fix themselves eventually (we expect within a few days). In the meantime, you can workaround it by explicitly specifying a version, such as `'43'` or `'44'` instead of `'current'` or `'upcoming'`. This is why the first link didn't work for you (it used `'current'`) and the second two did (they used versions `'43'` and `'44'` respectively).

Closing this bug as a duplicate of #2185.

**Closed as completed by grabks** 2016-03-02 19:51 UTC
Labels: duplicate

**Comment by gmorphis** [comment] 2016-03-02 19:54
I appreciate you as well, have a good one. Thanks again!
