### ISSUE TITLE
Gantt Chart is not working

### ISSUE THREAD

**Issue by trsnarayanan** [google/google-visualization-issues#2194] opened 2016-03-01 08:04 UTC
Till last week, I can see the gantt chart in my web page. Today it is missing. I tested, it throws "Object Required" error. Tried to use older API Version also. No use, please guide me to get back my gantt charts.

**Comment by grabks** [comment] 2016-03-01 14:50
Hi,

It sounds like you are experiencing the issues caused by caching and propagation delays of our latest release. These issues should fix themselves eventually. In the meantime, you can workaround it by explicitly specifying a version, such as `'43'` or `'44'` instead of `'current'` or `'upcoming'` as you currently do. If this workaround does not fix your problem, please post back with a code sample.

Closing this bug as a duplicate of #2185.

**Closed as completed by grabks** 2016-03-01 14:50 UTC
