### ISSUE TITLE
Bug: In Material Line Charts pointSize > 0 has no effect

### ISSUE THREAD

**Issue by orwant** [google/google-visualization-issues#1922] opened 2015-05-09 17:48 UTC
```
 In Material Line Charts pointSize > 0 has no effect

1. goto: Link: http://jsfiddle.net/api/post/library/pure/ 
2. add "pointSize: 5" to "materialOptions"
3. click "Run"

Regards Siebe Jongebloed

```

Original issue reported on code.google.com by `siebe.jongebloed` on 2015-03-16 12:08:35

**Comment by orwant** [comment] 2015-05-09 17:48
```
This is correct. The pointSize option is not yet supported for Material Charts.

Also, just so you're aware, the jsfiddle link you posted points to a blank jsfiddle.
In the future, please click the 'Save' button, and copy the link that you are redirected
to.
```

Original issue reported on code.google.com by `grabks@google.com` on 2015-03-16 13:37:40
- **Labels added**: Type-Enhancement
- **Labels removed**: Type-Defect

**Comment by grabks** [comment] 2016-01-13 15:55
Closing as a duplicate of https://github.com/google/google-visualization-issues/issues/2143

**Closed as completed by grabks** 2016-01-13 15:55 UTC
Labels: Priority-Medium, Type-Enhancement
