### ISSUE TITLE
Material Charts: slantedText, minTextSpacing, showTextEvery

### ISSUE THREAD

**Issue by orwant** [google/google-visualization-issues#1934] opened 2015-05-09 17:48 UTC
```
What would you like to see us add to this API?
I need to force showing every label of every column in material chart, but those three
options attributes 'slantedText' 'minTextSpacing' 'showTextEvery' doesn't seem to work
at all. Is it because they're not implemented yet. If so, when will be these features
implemented and is there another solution for this issue? 


What component is this issue related to (PieChart, LineChart, DataTable,
Query, etc)?
Column Material Charts


*********************************************************
For developers viewing this issue: please click the 'star' icon to be
notified of future changes, and to let us know how many of you are
interested in seeing it resolved.
*********************************************************

```

Original issue reported on code.google.com by `JimmyAXE68` on 2015-03-25 09:09:59

**Comment by orwant** [comment] 2015-05-09 17:48
```
Only a subset of the corechart options are available in the new material charts, so
far.  But you can get the colors and fonts of the material design in the corecharts
by adding the option theme: 'material', and then you can keep using the other corechart
options.
```

Original issue reported on code.google.com by `dlaliberte@google.com` on 2015-03-25 12:10:55

**Comment by grabks** [comment] 2016-01-13 15:54
Closing as a duplicate of https://github.com/google/google-visualization-issues/issues/2143

**Closed as completed by grabks** 2016-01-13 15:54 UTC
Labels: Type-Enhancement, Priority-Low
