### ISSUE TITLE
Google charts: coloum charts: Cannot read property 'arrayToDataTable' of undefined

### ISSUE THREAD

**Issue by anotherGoogleFan** [google/google-visualization-issues#2206] opened 2016-03-07 07:34 UTC
I wrote my html using google charts and totally imitate by the example that supported google. The pictures can be shown correctly, but there always be an error. I don't know why.

![02da5341-f25b-4e6c-b838-a1ad997daced](https://cloud.githubusercontent.com/assets/6881899/13563137/00549854-e47a-11e5-93ad-4ac0fd499cfc.jpg)

code here:
<html>
    <head>
        <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
        <script type="text/javascript">
            google.charts.load('current', {'packages':['bar']});
            google.charts.setOnLoadCallback(drawChart);

```
        function doDraw(obj)
        {
            var data = google.visualization.arrayToDataTable(obj.content);
            var option = {
                chart: {
                    title: obj.name,
                    subtitle: '',
                }
            };
            var div = document.createElement("div");
            div.style.width = 1500;
            div.style.height = 500;
            var chart = new google.charts.Bar(div);
            document.body.appendChild(div);
            chart.draw(data, option);
        }

        function drawChart() {
            var jsonContent = {"click":[{"Total":60,"Valid":50,"Send":40,"Kafka":30,"Mongo":20,"Mysql":10,"Start":"2016-03-04T20:00:00Z","End":"2016-03-04T21:00:00Z"}],"m.conversion":[{"Total":60,"Valid":50,"Send":40,"Kafka":30,"Mongo":20,"Mysql":10,"Start":"2016-03-04T20:00:00Z","End":"2016-03-04T21:00:00Z"}],"m.impression":[{"Total":60,"Valid":50,"Send":40,"Kafka":30,"Mongo":20,"Mysql":10,"Start":"2016-03-04T20:00:00Z","End":"2016-03-04T21:00:00Z"}],"m.request":[{"Total":60,"Valid":50,"Send":40,"Kafka":30,"Mongo":20,"Mysql":10,"Start":"2016-03-04T20:00:00Z","End":"2016-03-04T21:00:00Z"}],"m.response":[{"Total":60,"Valid":50,"Send":40,"Kafka":30,"Mongo":20,"Mysql":10,"Start":"2016-03-04T20:00:00Z","End":"2016-03-04T21:00:00Z"}],"m.transaction":[{"Total":60,"Valid":50,"Send":40,"Kafka":30,"Mongo":20,"Mysql":10,"Start":"2016-03-04T20:00:00Z","End":"2016-03-04T21:00:00Z"}],"m2.conversion":[{"Total":60,"Valid":50,"Send":40,"Kafka":30,"Mongo":20,"Mysql":10,"Start":"2016-03-04T20:00:00Z","End":"2016-03-04T21:00:00Z"}],"m2.online.click":[{"Total":60,"Valid":50,"Send":40,"Kafka":30,"Mongo":20,"Mysql":10,"Start":"2016-03-04T20:00:00Z","End":"2016-03-04T21:00:00Z"}],"m2.online.impression":[{"Total":60,"Valid":50,"Send":40,"Kafka":30,"Mongo":20,"Mysql":10,"Start":"2016-03-04T20:00:00Z","End":"2016-03-04T21:00:00Z"}],"m2.online.request":[{"Total":60,"Valid":50,"Send":40,"Kafka":30,"Mongo":20,"Mysql":10,"Start":"2016-03-04T20:00:00Z","End":"2016-03-04T21:00:00Z"}],"m2.online.response":[{"Total":60,"Valid":50,"Send":40,"Kafka":30,"Mongo":20,"Mysql":10,"Start":"2016-03-04T20:00:00Z","End":"2016-03-04T21:00:00Z"}]};    
            for (var i = 0; i < Object.keys(jsonContent).length; i++)
            {
                var jsonKey = Object.keys(jsonContent)[i];
                var tableJson = eval("jsonContent['" + jsonKey + "']");
                var hourly = new Object();
                hourly.name = jsonKey + ".Hourly";
                hourly.content = new Array();
                hourly.content[0] = new Array("Hour", "Total", "Valid", "Send", "Kafka", "Mongo");
                var daily = new Object();
                daily.name = jsonKey + ".Hourly";
                daily.content = new Array();
                daily.content[0] = new Array("Day", "Total", "Valid", "Send", "Kafka", "Mongo");
                for (var tableIndex = 0; tableIndex < tableJson.length; tableIndex ++)
                {
                    var start = new Date(tableJson[tableIndex].Start);
                    var end = new Date(tableJson[tableIndex].End);
                    var hourTime = 3600000; // 3600000 = 60 * 60 * 1000
                    var dayTime = 86400000; // 86400000 = 60 * 60 * 24 * 1000
                    if (end - start == hourTime)
                    {
                        var timef = start.getFullYear() + "年" + (start.getMonth() + 1) + "月" + start.getDate() + "日" + start.getHours() + "时"; 
                        hourly.content[hourly.content.length] = new Array(timef, tableJson[tableIndex].Total, tableJson[tableIndex].Valid, tableJson[tableIndex].Send, tableJson[tableIndex].Kafka, tableJson[tableIndex].Mongo);
                    }
                    else if(end - start == dayTime)
                    {
                        var timef = start.getFullYear() + "年" + (start.getMonth() + 1) + "月" + start.getDate() + "日";
                        daily.content[daily.content.length] =   new Array(timef, tableJson[tableIndex].Total, tableJson[tableIndex].Valid, tableJson[tableIndex].Send, tableJson[tableIndex].Kafka, tableJson[tableIndex].Mongo);
                    }
                }
                if (hourly.content.length > 1)
                {
                    doDraw(hourly);
                }
                if (daily.content.length >1)
                {
                    doDraw(daily);
                }
            }
        }
    </script>
</head>
<body>
    <body onload = "drawChart()">
</body>
```

</html>

**Comment by anotherGoogleFan** [comment] 2016-03-07 07:38
eh   I don't know why can't see the html code.  But in the edit mode I can see it, and it disappeared after  commited.

**Comment by grabks** [comment] 2016-03-07 15:02
@AnotherGoogleFans We'd love to help, but I'm afraid it's hard to do so without the code. Could you please try pasting it again, but within three backticks, like so: ````[code]````

**Comment by anotherGoogleFan** [comment] 2016-03-08 07:22
OK, code here:

`````` <html>
    <head>
        <title>数据统计计数</title>
        <link rel="shortcut icon" href="http://www.appcoachs.com/wp-content/uploads/300x100-logo-small-5-300x100.png">
        <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
        <script type="text/javascript">
            google.charts.load('current', {'packages':['bar']});
            google.charts.setOnLoadCallback(drawChart);

            function doDraw(obj)
            {
                var data = google.visualization.arrayToDataTable(obj.content);
                var option = {
                    chart: {
                        title: obj.name,
                        subtitle: '',
                    }
                };
                var div = document.createElement("div");
                div.style.width = 1500;
                div.style.height = 500;
                var chart = new google.charts.Bar(div);
                document.body.appendChild(div);
                chart.draw(data, option);
            }

            function drawChart() {
                var jsonContent = {"click":[{"Total":60,"Valid":50,"Send":40,"Kafka":30,"Mongo":20,"Mysql":10,"Start":"2016-03-04T20:00:00Z","End":"2016-03-04T21:00:00Z"}],"m.conversion":[{"Total":60,"Valid":50,"Send":40,"Kafka":30,"Mongo":20,"Mysql":10,"Start":"2016-03-04T20:00:00Z","End":"2016-03-04T21:00:00Z"}],"m.impression":[{"Total":60,"Valid":50,"Send":40,"Kafka":30,"Mongo":20,"Mysql":10,"Start":"2016-03-04T20:00:00Z","End":"2016-03-04T21:00:00Z"}],"m.request":[{"Total":60,"Valid":50,"Send":40,"Kafka":30,"Mongo":20,"Mysql":10,"Start":"2016-03-04T20:00:00Z","End":"2016-03-04T21:00:00Z"}],"m.response":[{"Total":60,"Valid":50,"Send":40,"Kafka":30,"Mongo":20,"Mysql":10,"Start":"2016-03-04T20:00:00Z","End":"2016-03-04T21:00:00Z"}],"m.transaction":[{"Total":60,"Valid":50,"Send":40,"Kafka":30,"Mongo":20,"Mysql":10,"Start":"2016-03-04T20:00:00Z","End":"2016-03-04T21:00:00Z"}],"m2.conversion":[{"Total":60,"Valid":50,"Send":40,"Kafka":30,"Mongo":20,"Mysql":10,"Start":"2016-03-04T20:00:00Z","End":"2016-03-04T21:00:00Z"}],"m2.online.click":[{"Total":60,"Valid":50,"Send":40,"Kafka":30,"Mongo":20,"Mysql":10,"Start":"2016-03-04T20:00:00Z","End":"2016-03-04T21:00:00Z"}],"m2.online.impression":[{"Total":60,"Valid":50,"Send":40,"Kafka":30,"Mongo":20,"Mysql":10,"Start":"2016-03-04T20:00:00Z","End":"2016-03-04T21:00:00Z"}],"m2.online.request":[{"Total":60,"Valid":50,"Send":40,"Kafka":30,"Mongo":20,"Mysql":10,"Start":"2016-03-04T20:00:00Z","End":"2016-03-04T21:00:00Z"}],"m2.online.response":[{"Total":60,"Valid":50,"Send":40,"Kafka":30,"Mongo":20,"Mysql":10,"Start":"2016-03-04T20:00:00Z","End":"2016-03-04T21:00:00Z"}]};    
                for (var i = 0; i < Object.keys(jsonContent).length; i++)
                {
                    var jsonKey = Object.keys(jsonContent)[i];
                    var tableJson = eval("jsonContent['" + jsonKey + "']");
                    var hourly = new Object();
                    hourly.name = jsonKey + ".Hourly";
                    hourly.content = new Array();
                    hourly.content[0] = new Array("Hour", "Total", "Valid", "Send", "Kafka", "Mongo");
                    var daily = new Object();
                    daily.name = jsonKey + ".Hourly";
                    daily.content = new Array();
                    daily.content[0] = new Array("Day", "Total", "Valid", "Send", "Kafka", "Mongo");
                    for (var tableIndex = 0; tableIndex < tableJson.length; tableIndex ++)
                    {
                        var start = new Date(tableJson[tableIndex].Start);
                        var end = new Date(tableJson[tableIndex].End);
                        var hourTime = 3600000; // 3600000 = 60 * 60 * 1000
                        var dayTime = 86400000; // 86400000 = 60 * 60 * 24 * 1000
                        if (end - start == hourTime)
                        {
                            var timef = start.getFullYear() + "年" + (start.getMonth() + 1) + "月" + start.getDate() + "日" + start.getHours() + "时"; 
                            hourly.content[hourly.content.length] = new Array(timef, tableJson[tableIndex].Total, tableJson[tableIndex].Valid, tableJson[tableIndex].Send, tableJson[tableIndex].Kafka, tableJson[tableIndex].Mongo);
                        }
                        else if(end - start == dayTime)
                        {
                            var timef = start.getFullYear() + "年" + (start.getMonth() + 1) + "月" + start.getDate() + "日";
                            daily.content[daily.content.length] =   new Array(timef, tableJson[tableIndex].Total, tableJson[tableIndex].Valid, tableJson[tableIndex].Send, tableJson[tableIndex].Kafka, tableJson[tableIndex].Mongo);
                        }
                    }
                    if (hourly.content.length > 1)
                    {
                        doDraw(hourly);
                    }
                    if (daily.content.length >1)
                    {
                        doDraw(daily);
                    }
                }
            }
        </script>
    </head>
    <body>
        <body onload = "drawChart()">
    </body>
</html>```
``````

**Comment by grabks** [comment] 2016-03-08 14:59
Thank you for posting the code. You issue has to do with the facts that:
1) you have two body tags (one `<body>` and another `<body onload ...>`
2) you're setting an onload handler for the body. This means that: a) `drawChart` will execute twice (once from your `onload` handler and once from `google.charts.setOnLoadCallback(...)`) and b) one of those `drawChart` executions will happen before the content has actually loaded.

Closing this issue, as this is not a bug in Google Charts. I'd be happy to continue helping you if my explanation was insufficient.

**Closed as completed by grabks** 2016-03-08 14:59 UTC

**Comment by julioAzocar** [comment] 2023-03-07 00:22
me salia el mismo error lo solucione invocando a la funcion sin () en drawChart

//google.charts.setOnLoadCallback(drawChart());->error
google.charts.setOnLoadCallback(drawChart);->ok
