### ISSUE TITLE
Org Chart: Documentation requires update

### ISSUE THREAD

**Issue by simonbbrown** [google/google-visualization-issues#2196] opened 2016-03-01 22:06 UTC
I was recently trying to intergrate Org Charts into my site, and was going off the example used on page here:
https://developers.google.com/chart/interactive/docs/gallery/orgchart

I got lots of a javascript errors whilst looking into that code example. The chart would work sometimes but mostly not.

After a while I inspected the working example and found that your working example uses a different loader.

Exisiting Example:
`google.charts.load('current', {packages:["orgchart"]});
      google.charts.setOnLoadCallback(drawChart);`

Embedded Example:
`google.load('visualization', '1', {packages:['orgchart']});
google.setOnLoadCallback(drawChart);`

When I switched my version over to the embedded example I have no issues. However I also had to switch the loading library from "https://www.gstatic.com/charts/loader.js" to "https://www.google.com/jsapi"

I'm sure other people are probably having issues with the provided example.

**Comment by nbering** [comment] 2016-03-02 02:09
May be duplicate of #2185. Switching to the old loader would also solve this issue. This is caused by a recent release of the library which seems to be breaking because of some caching issues. It should just fix itself soon, but changing from loading 'current' to '43' or '44' seems to fix the problem for most people.

**Comment by grabks** [comment] 2016-03-02 15:13
@simonbbrown `google.charts.load` is the correct thing to use. Do not switch to `google.load`, as we are no longer pushing new versions to `/jsapi`. We are having caching issues with the newest release, so `'current'` is currently broken. This is a spurious error, and should fix itself soon (over the next few days), and we will try to be more careful with our releases in the future to prevent these types of issues from occurring.

As @nbering said, switching the version to `'43'` or `'44'` should fix the problem for you, but keep in mind that you will have to switch your loader back to `google.charts.load`.

Marking this bug as a duplicate of #2185 and closing.

**Closed as completed by grabks** 2016-03-02 15:13 UTC
Labels: duplicate
