### ISSUE TITLE
View Window not working in Google Chrome

### ISSUE THREAD

**Issue by JordanSinko** [google/google-visualization-issues#2068] opened 2015-10-05 17:04 UTC
Hi:

I am having issues with my view window in Google Chrome, where in IE it works perfectly. I have attached the two pictures from the two different browsers. The view window for this is { min: 50000, max: 90000 }. Any help would be greatly appreciated. 

Chrome:
![image](https://cloud.githubusercontent.com/assets/10212966/10287502/65873066-6b61-11e5-8bee-179c60158ce4.png)

IE
![image](https://cloud.githubusercontent.com/assets/10212966/10287529/9284a58a-6b61-11e5-8d00-ae84612e38eb.png)

**Comment by JordanSinko** [comment] 2015-10-05 17:13
Once I remove the base tag from my head section, it appears to work. Is there a workaround for this? It is necessary for me to use this base tag with my AngularJS application.

**Comment by dlaliberte** [comment] 2015-10-05 17:14
Hi Jordan,
The viewWindow range you specified should work, so I am curious why it might be working differently (wrong) on Chrome.  Could you point us at the actual page that demonstrates this problem, or create a jsfiddle that shows it?

**Comment by JordanSinko** [comment] 2015-10-05 17:15
Hi dlaliberte:

Please see my second comment.

**Comment by dlaliberte** [comment] 2015-10-05 17:19
Ah, the base tag difference.  Yes, that would explain what you are seeing, because the clipping rectangle is probably missing.  The newest release should fix it for you, once it comes out which might be today.

**Comment by JordanSinko** [comment] 2015-10-05 17:31
That's great to hear. The sooner the better (clients will be using the software tomorrow). Do you know of any work arounds that I may implement until then? I tried the below code - which I found online - but was unsuccessful. 

![image](https://cloud.githubusercontent.com/assets/10212966/10288180/44a5ca70-6b65-11e5-8d18-cf0ad69f34ad.png)

**Comment by dlaliberte** [comment] 2015-10-05 18:16
You can use the frozen version of v43 now, by changing how you load.  See the instructions at  https://developers.google.com/chart/interactive/docs/library_loading_enhancements#frozen-versions

I'm curious whether v43 works for you.  Now that I think about it, I believe the change we made will detect the correct URL to use and avoid the problems caused by the presence of the base tag, but I'm not sure about all the contexts this could happen in.

**Comment by JordanSinko** [comment] 2015-10-06 15:23
It appears that this worked for me in Google Chrome. Thanks for all your help on this.

**Comment by dlaliberte** [comment] 2015-10-06 15:53
Glad it works for you.  Closing this now, since the fix will show up for everyone soon.

**Closed as completed by dlaliberte** 2015-10-06 15:53 UTC
