### ISSUE TITLE
Google Chart is not unstable

### ISSUE THREAD

**Issue by tilttran** [google/google-visualization-issues#2193] opened 2016-03-01 07:51 UTC
Hi Admin,
Sometimes, I view my report which built by google chart API, It doesn't show anything, just a blank page. First time, I think the error is cause by my code but when I go to https://developers.google.com/chart/interactive/docs/gallery/columnchart, and your page does not show anything too. What's the problem with your server now? 
Please help me, It's emergency!!!
Thanks
Dinh

**Comment by grabks** [comment] 2016-03-01 14:49
Hi,

You are experiencing the issues caused by caching and propagation delays of our latest release. These issues should fix themselves eventually. In the meantime, you can workaround it by explicitly specifying a version, such as `'43'` or `'44'` instead of `'current'` or `'upcoming'` as you currently do.

Closing this bug as a duplicate of #2185.

**Closed as completed by grabks** 2016-03-01 14:49 UTC
Labels: duplicate
