### ISSUE TITLE
Annotating Google Material Bar Charts

### ISSUE THREAD

**Issue by vmvivek208** [google/google-visualization-issues#2037] opened 2015-08-25 06:35 UTC
Hello everyone,

I was trying to use role annotation in material bar charts, its's not working. Has anyone tried the same?

Thanks in advance,
Vivek Mishra

**Comment by grabks** [comment] 2015-08-25 13:45
Hi, annotations are not yet implemented in Material charts. We are working on it.

**Comment by vmvivek208** [comment] 2015-08-26 07:38
Hello,

Thanks for your reply.

Thanks & Regards
Vivek Mishra
Scientist-B
National Informatics Center
Mob no:-+919873205937

**Comment by grabks** [comment] 2016-01-13 15:54
Closing as a duplicate of https://github.com/google/google-visualization-issues/issues/2143

**Closed as completed by grabks** 2016-01-13 15:54 UTC

**Comment by tamtam22** [comment] 2016-05-31 13:19
Hi, is annotations working on material google charts yet?

**Comment by jonsgreen** [comment] 2017-05-12 21:19
Any updates?

**Comment by borconi** [comment] 2019-05-30 14:24
No offence guys but it's 2019 and this still does not work... pretty bad for a company with reputation like Google...

**Comment by isaacrbeam** [comment] 2019-05-30 14:50
I agree with you @borconi

**Comment by qlerebours** [comment] 2019-06-18 09:12
It would be very usefull. Any workaround to annotate a material chart ?
