### ISSUE TITLE
Bug: 'google.visualization.DataTable' is null or not an object

### ISSUE THREAD

**Issue by orwant** [google/google-visualization-issues#1630] opened 2015-05-09 17:24 UTC
```
I need load the google map in our application. Below is my script.
Script:
<script type="text/javascript" src="https://www.google.com/jsapi"></script>
<script type="text/javascript">
if(document.URL.indexOf("saw.dll?Answers") == -1)
    google.load('visualization', '1', {packages: ['geomap']});
    google.setOnLoadCallback(drawGeo);


    function drawGeo() {

     var data = new google.visualization.DataTable();
      data.addColumn('string', 'Country');
      data.addColumn('number', 'Value');
      var myGeoArray=[];
      myGeoArray.push(["@1".replace("  "," "),@2]);
data.addRows(myGeoArray);
     var options = {};
      options['height'] = '400px';
      options['width'] = '400px';
      options['region'] = '@{p_country_code}';
      options['colors'] = [0x2ECCFA, 0x2E9AFE, 0x2E64FE,0x2E2EFE,0x642EFE,0xCC2EFA];
      options['dataMode'] = 'markers';
      options['showLegend'] = 'true';

      var container = document.getElementById('div_Geo');
      var geomap = new google.visualization.GeoMap(container);

      geomap.draw(data, options);

    };

drawGeo();

if(document.URL.indexOf("saw.dll?Answers") == -1)
{   google.setOnLoadCallback(drawGeo);}

  </script>

<style>
.preloader {
    height:400px; width:400px; background:url(res/s_blafp/images/ajax-loader.gif) center
center no-repeat;
}
</style>
<div id="div_Geo">Loading Map...</div>

I use IE 8.0 to open the map and it is very slow to load the map. And it also cannot
load successfully.

The first time the mapping will load very slow.
Then i refresh the page will show a warnning in the IE status:
'google is undefined'
Then refresh again, it still show a warning in the IE status:
'google.visualization.DataTable' is null or not an object

I have let our security check we didn't do anly block setup.

```

Original issue reported on code.google.com by `amethyst1022` on 2014-06-23 08:41:16

**Comment by orwant** [comment] 2015-05-09 17:24
```
Hello, the GeoMap is highly deprecated and should not be used by anyone. Please use
the GeoChart instead. the documentation for the GeoChart can be found here: https://developers.google.com/chart/interactive/docs/gallery/geochart
```

Original issue reported on code.google.com by `grabks@google.com` on 2014-06-23 13:41:28

**Comment by electronicsguy** [comment] 2016-02-01 19:11
The problem exists sporadically with 'geocharts' as well.

**Comment by grabks** [comment] 2016-02-01 19:21
@electronicsguy Can you create a jsfiddle (or something) that reproduces the issue? I really can't imagine how this might occur.

**Comment by electronicsguy** [comment] 2016-02-01 22:56
@grabks I described the problem here: [SO](http://stackoverflow.com/questions/35121785/google-visualization-undefined-for-setonloadcallback/35131519?noredirect=1#comment57997017_35131519). There's a JSFiddle code there, which is similar to what I'm using. My code is in a Google apps hosted web-app. I'll see if I can share it. The problem, occurs sporadically.

**Comment by grabks** [comment] 2016-02-02 14:42
@electronicsguy I don't see any jsfiddles in that SO post. If you're the person asking the question, then you need to be using `google.charts.setOnLoadCallback` instead of `google.setOnLoadCallback` if you use `google.charts.load` instead of `google.load`. The problem may occur sporadically, but the usage may be incorrect, which is what we're looking for. Likewise, if this is an actual bug that we can fix, we need to be able to reproduce the issue in order to look into a fix.

**Comment by electronicsguy** [comment] 2016-02-02 21:58
@grabks Please see the first answer. The "run code snippet" is right there. Yes I am indeed using _google.charts.setOnLoadCallback_ as mentioned in the documentation. However, I was using google.load instead of google.charts.load. I'll make that right and report back.

**Comment by grabks** [comment] 2016-02-02 22:01
So you're saying that the code in the first example fails for you intermittently? I'd expect it to work.

**Comment by electronicsguy** [comment] 2016-02-02 22:09
Yes fails intermittently, esp. on IE. Here's a public link I made to the web-app: [web-app]

Could you see if it gives you the same problem? I haven't updated the second line to "google.charts" as yet, so its exactly as before. Permissions for the web-app are set to "execute as me", "who has access, everyone, including anonymous". I can reproduce the problem like this: 

Chrome: seems to be working most of the time, even in incognito mode. However, if you refresh 5-6 times, the geomap won't appear and there'll be a error alert

IE 11: alert always

I don't really care about making it work reliably in IE, but I was just curious and so tried it out. I don't have firefox results as of now will post them in a bit.

**Comment by grabks** [comment] 2016-02-02 22:18
Please let me know when you fix it to be 'google.charts.setOnLoadCallback', since that is quite significant to the issue (as has been mentioned numerous times now), and is the lowest hanging fruit. If that doesn't fix the issue, report back.

**Comment by electronicsguy** [comment] 2016-02-03 05:33
@grabks Ok so i made the changes and it is working for the past 3 hours correctly in Chrome and IE 11. thank you for your help.

**Comment by grabks** [comment] 2016-02-03 14:39
Good to hear. Closing this bug, as it appears to be due to user error.

**Closed as completed by grabks** 2016-02-03 14:39 UTC
Labels: Type-Defect, Priority-Medium
