### ISSUE TITLE
multiple chart on same page using material

### ISSUE THREAD

**Issue by hard1880** [google/google-visualization-issues#2104] opened 2015-11-12 10:37 UTC
Hello, 
i'm trying to have more than one meterial chart in a page but only one is rendered ,which one it's a random choice.

Regards

Chrome version 46.0.2490.80 m
[code.txt](https://github.com/google/google-visualization-issues/files/32755/code.txt)

**Comment by grabks** [comment] 2015-11-12 14:57
This bug is a duplicate of issue [2066](https://github.com/google/google-visualization-issues/issues/2066).

As has been discussed in that thread, it is a known issue that charts are broken in versions 1.0 and 1.1. We have been having numerous issues pushing to /jsapi, and so we haven't fixed the bug there. You can get the newest version of Google Charts by using [frozen versions](https://developers.google.com/chart/interactive/docs/library_loading_enhancements#frozen-versions) and loading version 43. We will soon add the ability to load the 'latest' frozen version as well.

If you are already using version 43, and are still seeing this issue, please post back and we will investigate.

**Closed as completed by grabks** 2015-11-12 14:57 UTC
Labels: duplicate
